---
galaxy_info:
  author: "heatmiser"
  role_name: kvm_host_performance
  namespace: elise
  description: "Apply IBM KVM hypervisor performance best practices: tuned, huge pages, KVM module params, Intel IOMMU"
  license: GPL-3.0-only
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "9"

dependencies: []
...
