---
galaxy_info:
  author: "heatmiser"
  role_name: kvm_setup_libvirt
  namespace: elise
  description: "Configure libvirtd, bridge network, firewall, and define libvirt pool/network variables"
  license: GPL-3.0-only
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "9"

dependencies: []
...
