---
name: Ansible Lint

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install collection dependencies
        run: ansible-galaxy collection install -r collections/requirements.yml

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25
...
